# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5990fd503563a8d51546c03631ef65b5b6e6015c33a6f5a18f4558381cf371f413654eebc471121bca362f785363653413fdca064935f9e639c5e7246a8a076

test:
  secret_key_base: d13f207caf2efaf7b081cd1d5ee5124e00abdd2b79f50a36d9b13e1593c1c647ed1a9bf150a4ca67b43cc973380795ec168e6043277067343fe729e127208d43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
